# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudogene', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmodel',
            name='field3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
